### PR TITLE
feat: Add async support

### LINKED ISSUE #74: Request: Add async support
Async support (maybe via aiorequests/aiohttp?) would be very appreciated. Esp since some of the predictions can take a while to complete.

### PR DESCRIPTION
**Pull request by creatorrr**
Closes #74 

### Example:

```python
In [2]: import replicate

In [3]: model = replicate.models.get("creatorrr/instructor-large")

In [4]: version = await model.versions.get_async("bd2701dac1aea9d598bda71e6ae56b204287c0
   ...: a79e2cadf96b1393127d044495")

In [5]: inputs = {
   ...:     # Text to embed
   ...:     'text': "Hello world! How are you doing?",
   ...:
   ...:     # Embedding instruction
   ...:     'instruction': "Represent the following text",
   ...: }

In [6]: output = await version.predict_async(**inputs)

In [7]: output
Out[7]:
{'result': [[-0.008334644138813019, ... ]]}

```

### CODE REVIEW

**Comment by proksi21** [comment]
hey guys, approve it please, we need async api

**Comment by creatorrr** [comment]
@bfirsh request for a review

**Comment by GenifeG** [comment]
```python
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_async/connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_async/http11.py", line 112, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_async/http11.py", line 91, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_async/http11.py", line 155, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_async/http11.py", line 191, in _receive_event
    data = await self._network_stream.read(
  File "/usr/local/lib/python3.10/dist-packages/httpcore/backends/asyncio.py", line 31, in read
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ReadError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/host/servers/bots/adventgpt/main.py", line 437, in improve
    output = await improve_ver.predict_async(**inputs)
  File "/home/host/servers/bots/adventgpt/replicate-python/replicate/version.py", line 37, in predict_async
    prediction = await self._client.predictions.create_async(version=self, input=kwargs)
  File "/home/host/servers/bots/adventgpt/replicate-python/replicate/prediction.py", line 144, in create_async
    resp = await self._client._request_async(
  File "/home/host/servers/bots/adventgpt/replicate-python/replicate/client.py", line 101, in _request_async
    resp = await client.request(method, self.base_url + path, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadError
```
At the moment, even 2 tasks at the same time, he can not withstand.

I'm not sure what I'm saying, so I'm attaching my code:

CODE:
```python
os.environ[str("REPLICATE_API_TOKEN")] = "..."
...

async def replicate_load():
    global improve_ver
    improve_model = replicate.models.get("xinntao/realesrgan")
    improve_ver = await improve_model.versions.get_async("1b976a4d456ed9e4d1a846597b7614e79eadad3032e9124fa63859db0fd59b56")

@bot.event
async def on_ready():
    await replicate_load()
    
async def....
    try:
        inputs = {
            # Input
            'img': f'{attachment.url}',

            'version': "General - RealESRGANplus",

            'scale': 8,

            'face_enhance': True,

            'tile': 0,
        }

        output = await improve_ver.predict_async(**inputs)
        embed = discord.Embed(title="Photo:", color=discord.Colour.blurple()).set_image(url=output)
        await msg.edit(embed=embed)
    except Exception as e:
        print(traceback.format_exc())
```

**Comment by GenifeG** [comment]
I reinstalled all dependencies - the problem remained

**Comment by creatorrr** [comment]
@GenifeG can you please share a github gist to reproduce the error? I wrote a simple test and that seems to be passing

**Comment by GenifeG** [comment]
At the moment I can't. 

Please use the model from my code in the test, and run the function twice with an interval of, for example, 2 seconds (when the first one is not yet ready)

**Comment by GenifeG** [comment]
@creatorrr 
```python
import asyncio
import os
import traceback
import replicate

os.environ[str("REPLICATE_API_TOKEN")] = "YOUR_API_KEY"


async def replicate_load():
    global improve_ver
    improve_model = replicate.models.get("xinntao/realesrgan")
    improve_ver = await improve_model.versions.get_async(
        "1b976a4d456ed9e4d1a846597b7614e79eadad3032e9124fa63859db0fd59b56")


asyncio.run(replicate_load())


async def process():
    await asyncio.sleep(3)
    print(66)
    try:
        inputs = {
            # Input
            'img': f'https://media.discordapp.net/attachments/640960911204548648/1089223567746551889/image.png',

            'version': "General - RealESRGANplus",

            'scale': 3,
            'face_enhance': True,
            'tile': 0,
        }

        output = await improve_ver.predict_async(**inputs)
        print(output)
    except Exception:
        print(traceback.format_exc())


async def main():
    tasks = []
    for i in range(2):
        tasks.append(asyncio.create_task(process()))
        await asyncio.sleep(2)
    await asyncio.gather(*tasks)


asyncio.run(main())
```

Use it for test. Thanks!

**Comment by GenifeG** [comment]
Any changes?

**Comment by issafuad** [comment]
Hi is this going to be merged soon ? could really use the async support . many thanks

**Comment by pinktoadette** [comment]
Is there an update?

**Comment by Techming** [comment]
Hey @creatorrr  Any updates to this PR? Is it idle? Many thanks.

**Comment by creatorrr** [comment]
@Techming  idle unfortunately. I'm not using this lib anymore so not able to find time to update this. Any takers?

**Comment by mattt** [comment]
Thanks for your contribution, @creatorrr, and to everyone else for your interest. Apologies for the radio silence. 

I have an alternative implementation for async support in the [`async` branch]. It's effectively a rewrite of the current library, so I'm working to incrementally pull in functionality to minimize breaking changes. The first step towards that is #147, which replaces requests with httpx, which has async support.

**Comment by Techming** [comment]
Thanks @creatorrr for your previous work! and thank you @mattt for the updates and taking over. It seems that #147 has been ready for review for a couple of weeks and I'm wondering if there will be new features added to that PR or if we are simply waiting for review and approval. Thanks.

**Comment by mattt** [comment]
Hi @creatorrr. Following up on https://github.com/replicate/replicate-python/pull/76#issuecomment-1738827381 —

I just merged #193, which implements async support. One notable difference in this API is that the naming convention uses `async` as a method name prefix, rather than a suffix. Otherwise, it should be a drop-in replacement for your fork or existing synchronous usage.

Thank you again for contributing this PR. Please let me know if you see any ways we can improve our implementation of async.

**Pull request closed without merging**
